run-name: Build code for Assignment 7

on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - 'A7/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: ttk4255
          environment-file: environment.yml

      - name: Check Conda Environment Status
        run: |
          conda info
          conda list

      - name: Run "A7, Main"
        run: python A7/python/main.py

      - name: Upload "A7" Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: A7-Artifacts-${{ runner.os }}
          path: |
            A7/plots/**

      - name: Upload "A7" Code
        uses: actions/upload-artifact@v4
        with:
          name: A7-Code-${{ runner.os }}
          path: |
            A7/python/*.py
            !A7/python/common.py
            !A7/python/task41_calc.py
