run-name: Build code

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: ttk4255
          environment-file: environment.yml

      - name: Check Conda Environment Status
        run: |
          conda info
          conda list

      - name: Run "A4, Task2.py"
        run: python A4/python/task2.py

      - name: Run "A4, Task3.py"
        run: python A4/python/task3.py

      - name: Run "A4, Task4.py"
        run: python A4/python/task4.py

      - name: Create A4 Code .ZIP
        run: python A4/python/create_submission_zip.py

      - name: Upload "A4" Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: A4-PlotsAndCode-${{ runner.os }}
          path: |
            A4/plots/**
            A4/*.zip
